CHANGELOG.md
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/diff/compare.go
version/version.go

- **What does the PR do?** *Fixes Nil pointer and also restricts environment-operator to only deploy k8s resources when a deployment has been made for that service*
- **What automated testing exists for this change?** *unit tests updated*
- **Is there documentation?** *N/A

BITE-1634: GLP Fix

---

CHANGELOG.md
docs/Environment_Config.md
pkg/bitesize/config.go
pkg/bitesize/environment_test.go
pkg/bitesize/service.go
pkg/bitesize/validation.go
pkg/bitesize/validation_test.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/service_map.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go
test/assets/environments.bitesize
test/assets/environments2.bitesize

BITE-1736
https://github.com/pearsontechnology/environment-operator/blob/BITE-1736/docs/Environment_Config.md
Updated external_url parameter description
No

Support services with multiple external URLs

---

CHANGELOG.md
pkg/bitesize/service.go
pkg/cluster/cluster.go
pkg/cluster/service_map.go
pkg/reaper/reaper.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go

rework external_url

---

CHANGELOG.md
docs/Environment_Config.md
pkg/bitesize/service.go
pkg/cluster/cluster_test.go
pkg/cluster/service_map.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go
test/assets/environments.bitesize
version/version.go

support service backend override

---

CHANGELOG.md
docs/Environment_Config.md
pkg/bitesize/config.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go

https://agile-jira.pearson.com/browse/BITE-1902

support downward api fieldPath env vars

---

CHANGELOG.md
pkg/git/git.go

https://agile-jira.pearson.com/browse/BITE-1941

fix intermittent panic issue in git pkg

---

.travis.yml
travis/releaseTagging.sh

new release hipchat notification

---

CHANGELOG.md
pkg/cluster/service_map.go

fix backend port wrong diff generated

---

CHANGELOG.md
pkg/util/k8s/persistent_volume_claim.go

preserve volume name on pvc update

---

travis/releaseTagging.sh

- [] **Has the changelog been updated?**

fix notifyHipchat typos

---

CHANGELOG.md
version/version.go

release version 0.0.12

---

travis/releaseTagging.sh

fix hipchat notifications

---

CHANGELOG.md
pkg/bitesize/service.go
pkg/cluster/service_map.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go
version/version.go

BITE-2633 support setting http2 label on ingresses

---

CHANGELOG.md
pkg/cluster/service_map.go
version/version.go

fix ingress exists but the service is not defined issue

---

docs/Environment_Config.md

BITE-2587 document service type field

---

CHANGELOG.md

release version 0.0.13

---

docs/Private_Registry.md

BITE-2747 update docs with ECR usage

---

CHANGELOG.md
cmd/operator/main.go
pkg/cluster/cluster.go
pkg/diff/compare.go
pkg/git/git.go
pkg/git/pull.go
pkg/git/refresh.go
pkg/git/updates_exist.go
pkg/k8_extensions/types.go
pkg/reaper/reaper.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?
https://agile-jira.pearson.com/browse/BITE-4084
Refactoring (adding logs) and adding postgres crd support
- **What automated testing exists for this change?
Extended existing tests with environments.bitesize file in PR
No
Yes

BITE-4084: Adding postgres

---

CHANGELOG.md
pkg/cluster/cluster.go
version/version.go

- **What does the PR do?**
* Details can be found under BITE-4482 
- **What automated testing exists for this change?** 
* Unit tests are written under each package
- **Is there documentation?** 
* Yes
- **Any dependencies?** 
* No
* Yes

BITE-4482: Enable continuation of deployments

---

CHANGELOG.md
pkg/util/k8s/crd.go

- **What does the PR do?** *This fixes the CRD provision issue we are having with the new version*
- **What automated testing exists for this change?** *Unit tests are located under same package*
- **Is there documentation?** *Under docs folder*

BITE-4545: Fix nil pointer issue with CRDs

---

CHANGELOG.md
pkg/bitesize/service.go
pkg/cluster/cluster_test.go
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?** *BITE-4641*
- **What automated testing exists for this change?** *Existing unit tests*
- **Is there documentation?** *Under the project directory*

BITE-4641 Add support for complex data structures

---

CHANGELOG.md
environment.sample
example/sample_app/app/back/index.js
example/sample_app/app/back/package.json
pkg/bitesize/config.go
pkg/bitesize/service_test.go
pkg/bitesize/validation.go
pkg/bitesize/validation_test.go
pkg/cluster/cluster_test.go
pkg/cluster/service_map.go
pkg/reaper/reaper_test.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go
pkg/util/k8s/horizontal_pod_autoscaler.go
pkg/util/k8s/horizontal_pod_autoscaler_test.go
test/assets/environments.bitesize
test/assets/environments2.bitesize
version/version.go

BITE-4602 Add  HPA v2beta1 with custom metrics support

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

Added EO Support for SQS - ODY-158

---

example/sample_app/run_example.sh

- **What does the PR do?** 
Updates sample script to work without requiring DNS, which is a requirement for the way it's usually run (outside of the cluster containers).
- **What automated testing exists for this change?** none
- **Is there documentation?** No
- **Any dependencies?** No

docs: fix docs so work outside of in-cluster containers

---

CHANGELOG.md
docs/Probes.md

- **What does the PR do?** *Add missing docs for BITE-4993*
- **What automated testing exists for this change?** *N/A*

BITE-4993 Add missing documentation

---

docs/Environment_Config.md
docs/HPA.md
environment.sample

BITE-4776 HPA based on custom metrics docs

BITE-4776 HPA based on custom metrics docs

---

pkg/bitesize/validation.go
pkg/bitesize/validation_test.go
pkg/translator/kubemapper_test.go
pkg/util/k8s/horizontal_pod_autoscaler_test.go

- **What does the PR do?** 
BITE-4603 additional metrics tests

BITE-4603 additional metrics tests

---

integration.bitesize
pkg/cluster/cluster.go

BITE-4481 Add integration.bitesize, ignore HPA replica updates

---

CHANGELOG.md
version/version.go

- **What does the PR do?** ARGO-576: enables trace logging
- **What automated testing exists for this change?** None
- **Is there documentation?** No
- **Any dependencies?** (merged) https://github.com/pearsontechnology/environment-operator/pull/86

ARGO-576: Initiating a new release (trace logging)

---

CHANGELOG.md
pkg/reaper/reaper.go
version/version.go

BITE-5359 add HPA reaper

---

CHANGELOG.md
pkg/translator/kubemapper.go
version/version.go

- **What does the PR do?** *This will fix volume mount issue for init containers*
- **What automated testing exists for this change?** *Same tests can be applied*
- **Is there documentation?** *Same docs can be used*
- **Any dependencies?** *No*

Bite-5404 - Fix volume mount issue

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

ODY-120 Added S3

---

CHANGELOG.md
pkg/cluster/helpers.go
pkg/cluster/helpers_test.go
pkg/translator/kubemapper.go
version/version.go

- **What does the PR do?** *Fix the issue with probe 'period_seconds' not getting applied*
- **What automated testing exists for this change?** *Covered under unit tests*
- **Is there documentation?** *Yes. Under Probe in documents.*
- **Any dependencies?** *No*

BITE-5587 Fix probe issue with health checks

---

CHANGELOG.md
pkg/cluster/cluster.go
pkg/cluster/service_map.go
pkg/diff/compare.go
version/version.go

- **What does the PR do?** *Fix bitesize config changes not reflect in kubernetes objects with EO when HPA is enabled*
- **What automated testing exists for this change?** *Under unit tests*
- **Is there documentation?** *Bug fix, already documented under HPA*

BITE-5627 Fix change not reflecting issue

---

pkg/diff/compare.go

- **What does the PR do?** *Fix nil pointer issue raised on previous change*
- **What automated testing exists for this change?** *can use same unit tests*
- **Is there documentation?** *same docs*

BITE-5627 Fix nil pointer issue in probes

---

CHANGELOG.md
version/version.go

- **What does the PR do?** *Bump the version to add new changes since 1.2.6 didn't get updated*
- **What automated testing exists for this change?** *Already tested*
- **Is there documentation?** *Already documented*

BITE-5627 Bump version

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize

- **What does the PR do?** 
Corrects some typos in MSK
- **What automated testing exists for this change?**
test/assets/environments.bitesize has been updated
- **Is there documentation?**
SupportedCustomResources has been updated
- **Any dependencies?**
No
Yes

BITE-5517: AWS Managed Kafka (MSK)

---

CHANGELOG.md
pkg/k8_extensions/types.go
version/version.go

- **What does the PR do?** *Fix type case issue with helm controller*
- **What automated testing exists for this change?** *Already covered by existing tests*
- **Is there documentation?** *Yes, under docs*

BITE-6270 Fix type case issue with helm controller

---

docs/Create_Neptune_Cluster.md

- **What does the PR do?** *Documentation added for Neptune cluster creation*
- **What automated testing exists for this change?** *N/A*

Bite 5786 Documentation update for neptune cluster creation new parameters

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
version/version.go

This PR will add DynamoDB identifying capabilities to EO. 
- Adds DynamoDB CRD support for EO
- Test EO test cases by adding dynamodb crd configs. 
- No
- No
- Yes

Added DynamoDB Support with BITE-6578

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/translator/kubemapper.go
pkg/translator/kubemapper_test.go
version/version.go

- **What does the PR do?** *Enables support for TLS from Istio gateway side*
- **What automated testing exists for this change?** *Yes, under tests*
- **Is there documentation?** *Same docs can be used which are in the docs/istio*

BITE-6732 Add TLS support for Istio Gateway

---

docs/Create_DynmoDB_Cluster.md

- **What does the PR do?** *(BITE-6578, Added How DynamoDB is provisioned in Bitesize documentation)*
- **What automated testing exists for this change?** *N/A*

BITE-6578 DynamoDB CRD workflow documentation

---

CHANGELOG.md
pkg/bitesize/service.go
pkg/cluster/cluster.go
pkg/diff/compare.go
version/version.go

- **What does the PR do?** *In the previous PR the change detection mechanism for ExternalSecrets was not working due to the CRD client was not initialized in the correct namespace. This PR will fix the above-mentioned issue.*
- **What automated testing exists for this change?** *NA*
- **Is there documentation?** *Documentation was already added in the previous release*
- **Any dependencies?** *NA*

Fix changes always getting detected for ExternalSecrets

---

CHANGELOG.md
docs/Private_Registry.md
example/keycloak/keycloak-incluster-deployment.yaml
example/keycloak/operator-deployment.yaml
example/sample_app/operator-deployment-token.yaml
example/sample_app/operator-deployment.yaml
example/sample_app/operator-ingress.yaml
pkg/cluster/cluster_test.go
pkg/translator/kubemapper.go
pkg/util/k8s/horizontal_pod_autoscaler_test.go
pkg/util/k8s/statefulset.go
version/version.go

- **What does the PR do?** *Fix the issues with deployment endpoints*
- **What automated testing exists for this change?** *Same tests*
- **Is there documentation?** *Yes*

Fix issues with HPA APIs

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?** *Add Mongo Atlas CRD support*
- **What automated testing exists for this change?** *Added environment16.bitesize to test*
- **Is there documentation?** *only crd kind adding*
- **Any dependencies?** *no*

Add Mongo Atlas CRD support

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?** *This will allow EO to provision ES CRDs*
- **What automated testing exists for this change?** *under tests folder*
- **Is there documentation?** *Can refer the same unit test sample*

Add ES CRD support

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?** *Adds support to CloudFront CRD*
- **What automated testing exists for this change?** *Updated existing tests*

MAV-1647: Add CloudFront CRD support

---

CHANGELOG.md
pkg/k8_extensions/types.go
pkg/util/k8s/fake/crd_client.go
test/assets/environments.bitesize
version/version.go

- **What does the PR do?** *Adds support to Cronjob CRD*
- **What automated testing exists for this change?** *Updated existing tests*

add cronjob crd
